# Generated by Django 4.0.6 on 2022-09-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aparteman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titr', models.CharField(max_length=150, verbose_name='تیتر')),
                ('status_buy', models.CharField(choices=[('برای خرید', 'برای خرید'), ('برای اجاره', 'برای اجاره')], default='برای خرید', max_length=50, verbose_name='برای خرید/رهن و اجاره')),
                ('gheymat', models.PositiveIntegerField(default=0, verbose_name='قیمت')),
                ('gheymat_rahn', models.PositiveIntegerField(default=0, verbose_name='قیمت رهن')),
                ('gheymat_ejare', models.PositiveIntegerField(default=0, verbose_name='قیمت اجاره')),
                ('locations', models.TextField(verbose_name='ادرس اپارتمان')),
                ('sanad', models.CharField(choices=[('شش دانگ', 'شش دانگ'), ('مشاع', 'مشاع'), ('اصلاحات ارضی', 'اصلاحات ارضی')], default='شش دانگ', max_length=32, verbose_name='نوع سند')),
                ('andaze', models.PositiveIntegerField(default=0, verbose_name='متراژ')),
                ('tabaghe', models.PositiveIntegerField(verbose_name='طبقه')),
                ('tedad_tabaghe', models.PositiveSmallIntegerField(verbose_name='تعداد طبقه')),
                ('tedad_vahed_tabaghe', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد واحد در هر طبقه')),
                ('tedad_otagh', models.CharField(max_length=2, verbose_name='تعداد اتاق')),
                ('tedad_dastshoe', models.PositiveSmallIntegerField(verbose_name='تعداد سرویس بهداشتی')),
                ('sal_sakht', models.IntegerField(verbose_name='سال ساخت')),
                ('tozihat_karbar', models.TextField(verbose_name='توضیحات کاربر')),
                ('tozihat_khososy', models.TextField(blank=True, null=True, verbose_name='توضیحات خصوصی')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='عکس اصلی')),
                ('upload_time', models.DateField(auto_now=True, verbose_name='زمان ثبت')),
                ('parking', models.CharField(max_length=2, null=True)),
                ('ghabel_moaveze', models.BooleanField(default=False, verbose_name='قابل معاوضه؟')),
                ('vise', models.BooleanField(default=False, verbose_name='ویژه؟')),
                ('active', models.BooleanField(default=True, verbose_name='نمایش داده شود؟')),
                ('tahvie', models.BooleanField(default=False)),
                ('internet', models.BooleanField(default=False)),
                ('trass', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('bed', models.BooleanField(default=False)),
                ('micro', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('sahel', models.BooleanField(default=False)),
                ('system_garmayeshi', models.BooleanField(default=False)),
                ('sigary', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'اپارتمان',
                'verbose_name_plural': 'اپارتمان ها',
                'ordering': ['-upload_time'],
            },
        ),
    ]
