# Generated by Django 4.0.6 on 2022-09-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparteman',
            name='parking',
            field=models.BooleanField(default='False'),
        ),
    ]
