# Generated by Django 4.0.6 on 2022-09-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_aparteman_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aparteman_images',
            old_name='images',
            new_name='image',
        ),
    ]
